version: '3'


services:
  db:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=daw2024
      - POSTGRES_USER=alejandroRodriguez
      - POSTGRES_DB=DAW_rodriguez

    ports:
      - 5432:5432